#Config for metadataMonitor
[server]
server_url = https://play.im.dhis2.org/stable-2-40-6
server_username = admin
server_password = district
aggregate_dataset = oz5AHxQzsUd
monitor_data_element_group = yNpUqX1BiFC
